# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92ebb594fc3e3aff8b882f54b4209f408bddb703e09931e57516e9a13ab751ee1ca55b789396e51c31a15e4f2b5b70faf2ff0aa79d5e7bafa56a363bffdf5fde

test:
  secret_key_base: 5c0bc56a5403af615dedda7e183a5b672e22402fa1d2f8298fad563bee442050daed3495627cf4e17b0fbdb673b30a2e1612d654371d06651ff92aeee3e47524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
